---
title: "Final_report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Motivation:

Given the scenario of social distancing and temporary closure of movie theaters across the United States, the pandemic did hit the movie industry severly not only for a domestic market but also in a global scale. According to Comoscore, it has been a dramatic 76% drop in domestic box office in 2020 compared with the same point in 2019. Substantial resturcting in the movie industry urge the producers and directors to be effective and efficient as much as possible. Box-office prediction has never been such a crucial problem in the film industry, such that profitability is directly associated with strategy made by investors and producers. 

Our main goal is to:

*   use skinny to explore the association between the box-office gross and  other variables including genres, budget, and IMDb score
*   create word cloud, radar map on contributing factors
*   generate linear regression model to predict box-office revenue 


## Related Work:

#### **Related Work**

The following resources are a sample of what inspired this project.

1. "Here's how badly coronavirus has decimated the box office" *CNN*, October 14, 2020. [Link.](https://edition.cnn.com/2020/10/14/media/box-office-coronavirus/index.html)
2. "Disney-owned theaters? Masks with your ticket? Moviegoing could look quite different post-pandemic" *USA TODAY*, January 16, 2020. [Link.](https://www.usatoday.com/story/entertainment/movies/2020/06/14/future-moviegoing-could-coronavirus-kill-movie-theaters/3186292001/)
3. "Can there be a fairy-tale ending for Hollywood after COVID-19?" *WORLD ECONOMIC FORUM*, January 23, 2020. [Link.](https://www.weforum.org/agenda/2020/07/impact-coronavirus-covid-19-hollywood-global-film-industry-movie-theatres/)


## Intial Questions:

- What is the general trend of gross across time? Will this pattern vary for different genres?
- What is the association between Gross and other variables including IMDB_score, facebook_likes?
- Is director a significant predictor of Gross?
- the crude relationship between number of reviews and Gross


## Data

### *Data Sources*

* Primary data source: [Kaggle](https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset) 
* release ymd(year, month, date): [IMDb] (https://https://www.imdb.com/)

&nbsp;

### *Variables of interest*

##### **Outcomes**

- `gross`: total gross for the movies

##### **Candidate Predictors**

Variable name             | Data type | Variable explanation
--------------------------|-----------|---------------
`director_name`           |chr        |Name of the Director of the movie
`director_facebook_likes` |dbl        |Number of likes of the director on his/her Facebook Page
`actor_1_name`            |chr        |Primary actor starring in the movie
`actor_1_facebook_likes`  |dbl        |Number of likes of the Actor_1 on his/her Facebook Page
`cast_total_facebook_likes`|dbl       |Number of likes of the total casts on his/her Facebook Page
`movie_facebook_likes`    |dbl        |Number of likes of the movie on its Facebook Page
`duration`                |dbl        |Length for the movie
`genres`                  |chr|Total genres for the movie
`movie_title`             |chr|The title for the movie
`num_critic_for_reviews`  |dbl        |Number of the critic reviews for the movie
`num_voted_users`         |dbl        |Number of users who review for the movie
`num_user_for_reviews`    |dbl        |Number of users reviews for the movie
`language`|chr|Main language for the movie
`country`|chr|Country for the movie
`budget`|dbl|Total budget for the movie
`title_year`|dbl|Release year for the movie
`imdb_score`|dbl|Overall score for the movie on IMDB
`aspect_ratio`|dbl|Aspect ratio for the movie


&nbsp;

### *Data Cleaning*

- Keep only interested variables
- Manipulate `genres` and `plot_keywords` column:
  - Input example: "avatar|future|marine|native|paraplegic"
  - For model: 
    - Purpose: separate into multiple columns with 0 and 1
      - Find all the genres: `unique`, `unlist`, and `str_split`
      - Create a blank dataframe with all 0s
        - Columns number is equal to raw dataset
        - Row number is equal to genres types
      - Use for loop: test for all the movies, if it has the certain genres, change the corresponding number from 0 to 1
  - For shiny: `separate` + `pivot_longer`:
    - Purpose: all the original words as the filter for nearly all the plots
      - Use `separate` function to split the column into multiply sub-columns (g1-g8). 8 is the maximum genre type of a single film. By then, unused columns of a single film will be recorded as NA
      - Use `pivot_longer` to convert these sub-columns to the pattern as id – value. Then, we can clean the value column (drop NA) and ignore the id value. 
      - `plot_keywords` columns is treated same as this



